spring:
  activiti:
    #表示启动时检查数据库表，不存在则创建
    database-schema-update: true
    #表示哪种情况下使用历史表，这里配置为full表示全部记录历史，方便绘制流程图
    history-level: full
    #true表示使用历史表，如果不配置，则工程启动后可以检查数据库，只建立了17张表
    db-history-used: true
